# Generated by Django 2.1.4 on 2019-05-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=500)),
                ('date_publish', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
